packer {
  required_plugins {
    googlecompute = {
      source  = "github.com/hashicorp/googlecompute"
      version = "~> 1"
    }
  }
}

variable "machine_type" {
  type    = string
  default = "e2-medium"
}

variable "project_id" {
  type    = string
  default = "dev6225webapp"
}

variable "source_image" {
  type    = string
  default = "centos-stream-8-v20240110"
}

variable "ssh_username" {
  type    = string
  default = "centOS"
}

variable "zone" {
  type    = string
  default = "us-west4-b"
}

variable "credentials_file" {
  type    = string
  default = "serviceaccount.json"
}

locals { timestamp = regex_replace(timestamp(), "[- TZ:]", "") }

source "googlecompute" "autogenerated_1" {
  credentials_file = "${var.credentials_file}"
  disk_size        = 20
  image_name       = "centos-8-image-${local.timestamp}"
  machine_type     = "${var.machine_type}"
  project_id       = "${var.project_id}"
  source_image     = "${var.source_image}"
  ssh_username     = "${var.ssh_username}"
  zone             = "${var.zone}"
}



build {
  sources = ["source.googlecompute.autogenerated_1"]

  provisioner "file" {
    source      = "webapp"
    destination = "/tmp/webapp"
  }

  provisioner "file" {
    source      = "flaskapp.service"
    destination = "/tmp/flaskapp.service"
  }

  provisioner "file" {
    source      = "config.yaml"
    destination = "/tmp/opsconfig.yaml"
  }

  provisioner "shell" {
    script = "setup.sh"
  }

  post-processors {
    post-processor "manifest" {
      output     = "manifest.json"
      strip_path = true
    }
  }

}
